/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_geekeye_mobile_detection_1_0_0 */

#ifndef _Included_com_example_jni_geekeye_mobile_detection_1_0_0
#define _Included_com_example_jni_geekeye_mobile_detection_1_0_0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_geekeye_mobile_detection_1_0_0
 * Method:    DL_Init_Detection
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_geekeye_1mobile_1detection_11_10_10_DL_1Init_1Detection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jni_geekeye_mobile_detection_1_0_0
 * Method:    DL_Image_Detection
 * Signature: (Landroid/graphics/Bitmap;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jni_geekeye_1mobile_1detection_11_10_10_DL_1Image_1Detection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_jni_geekeye_mobile_detection_1_0_0
 * Method:    DL_Video_Detection
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jni_geekeye_1mobile_1detection_11_10_10_DL_1Video_1Detection
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
